import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/page'
import Footer from '@/components/footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='px-5 md:px-20 lg:px-40 flex flex-col justify-between bg-white'><Navbar></Navbar> </div>
        <div className='h-screen w-screen px-5 md:px-20 lg:px-40 flex flex-col justify-between '> {children}</div>
        <div className='px-5 md:px-20 lg:px-40 flex flex-col justify-between bg-white'><Footer></Footer></div>
      </body>
    </html>
  )
}
