"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/page'
import Footer from '@/components/footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='w-screen h-screen flex flex-col justify-between '>
          <div className='px-2 md:px-20 lg:px-40 flex flex-col justify-between bg-black text-white'><Navbar></Navbar> </div>
          <div className=' w-full h-full px-2 md:px-20 lg:px-40 flex flex-col justify-between my-7 overflow-y-scroll'> {children}</div>
          <div className='px-2 md:px-20 lg:px-40 flex flex-col justify-between bg-black text-white'><Footer></Footer></div>
        </div>
      </body>
    </html>
  )
}
